[workspace.package]
authors = ["Paul Lesur"]
categories = []
description = ""
edition = "2021"
license = "GPLv3"
readme = "README"
version = "0.1.0"

[workspace]
members = [
    "symbolrust",
    "symbolrust_macros",
    "symbolrust_repl",
]
resolver = "2"
