[package]
name = "symbolrust"
authors.workspace = true
categories.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
symbolrust_macros = { path = "../symbolrust_macros" }
ndarray = "0.15.6"
num-traits = "0.2.19"
